- .gitignore
- src/test/java/org/craftercms/studio/test/cases/DesignOfCreateSitePageTest.java
- src/test/java/org/craftercms/studio/test/cases/ValidationsOfCreateSiteFieldsTest.java
https://github.com/craftercms/craftercms/issues/128
https://github.com/craftercms/craftercms/issues/139
> Automation tests, ticket 128 and ticket 139

- src/test/java/org/craftercms/studio/test/cases/CancelCreateSiteProcessTest.java
- src/test/java/org/craftercms/studio/test/cases/LogOutTest.java
- src/test/java/org/craftercms/studio/test/pages/CreatePage.java
- src/test/resources/SharedUIElements.properties
https://github.com/craftercms/craftercms/issues/138 and https://github.com/craftercms/craftercms/issues/129
> Automation tests, ticket 138 and ticket 129

- src/test/java/org/craftercms/studio/test/cases/DesignOfPreviewPageTest.java
Automation test, ticket https://github.com/craftercms/craftercms/issues/143
> Automation test, ticket 143

- src/test/java/org/craftercms/studio/test/cases/CTDragAndDropTest.java
- src/test/java/org/craftercms/studio/test/cases/CTInputTest.java
- src/test/java/org/craftercms/studio/test/cases/CreateSiteEmptyTest.java
- src/test/java/org/craftercms/studio/test/cases/DeleteSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/LogOutTest.java
- src/test/java/org/craftercms/studio/test/cases/LoginTest.java
- src/test/java/org/craftercms/studio/test/pages/AdminConsolePage.java
- src/test/java/org/craftercms/studio/test/pages/CreatePage.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/resources/SharedUIElements.properties
Adapting the automation with empty blueprint, test cases: LoginTest, LogOutTest, CreateSiteEmptyTest, CTDragAndDropTest, CTInputTest.
> Adapting the automation with empty blueprint

- src/test/java/org/craftercms/studio/test/cases/CutPasteContentTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
test cases updated: CutPasteContentTest, some pages (dashboardPage), files and testsuite.xml
> Adapting the automation with empty blueprint.

- src/test/java/org/craftercms/studio/test/api/ForgotPasswordAPITest.java
- src/test/java/org/craftercms/studio/test/cases/AddNewContentLevelDescriptorTest.java
- src/test/java/org/craftercms/studio/test/cases/CancelCreateSiteProcessTest.java
- src/test/java/org/craftercms/studio/test/cases/CreateSiteEmptyTest.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/resources/SharedUIElements.properties
Working on automation test for api : forgot password 
Working on update some Web Elements identifier.(selectors, xpaths and ID)
> "API" Automation and update of Web Elements identifier.

- src/test/java/org/craftercms/studio/test/api/ChangePasswordAPITest.java
- src/test/java/org/craftercms/studio/test/api/CreateSiteAPITest.java
- src/test/java/org/craftercms/studio/test/api/ResetPasswordAPITest.java
- src/test/java/org/craftercms/studio/test/api/SyncFromRepoAPITest.java
Working on test cases: Change Password API, Creati Site API, Reset Password API, Sync From Repo API.
> Automation for APIs

- src/test/java/org/craftercms/studio/test/api/DeleteGroupAPITest.java
- src/test/java/org/craftercms/studio/test/api/GetUsersPerGroupAPITest.java
- src/test/java/org/craftercms/studio/test/api/UpdateGroupAPITest.java
> test cases: DeleteGroupAPI - GetUserPerSiteAPI - GetUsersPerSiteAPI - UpdateGroupAPI

- src/test/java/org/craftercms/studio/test/cases/PresetEachDesignTest.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/java/org/craftercms/studio/test/pages/UsersPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
… related to an specific part e.g: Dashboard, Site Config, Home, Contextual Navigation Bar, Content Types, Account Management
-Added and automated the test case: ContentTypesAddRepeatingGroupTest.java
-Improved some related methods to ContentTypesAddInputTest.java class
> -Reformat to the test cases package structure and automated ContentTypesAddRepeatingGroupTest test case

- pom.xml
- src/test/resources/ExecutionConstants.properties
- src/test/resources/testng.xml
Adding the last week test cases to testng.xml structure for execution:
-Add RepeatingGroup Control to an existing Content Type
-Add TextArea Control to an existing Content Type
-Create Site with WebSiteEditorial Blueprint
-Crafter3LoadTest
Changing web browser from Chrome to PanthomJS
> Resolving issues with PanthomJS dependecies on pom.xml and adding test cases to testing.xml structure

- pom.xml
- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testngLoadTestSuite.xml
…tomated)
Modified the pom.xml structures for mvn execution of a given testng.xml file... e.g: `mvn clean test -Dfile=src/test/resources/testngLoadTestSuite.xml` when user needs to execute the crafter3loadtest test-suite
Fixed some issues with selectors on DashboardPage.java
> Added the xml file for indepent test suite for Crafter3 Load Test and Some fixes on css selectors

- pom.xml
- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Craftercms1248Test.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceUsingConfiguredXMLList.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/pages/LoginPage.java
- src/test/java/org/craftercms/studio/test/utils/FilesLocations.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/ExecutionConstants.properties
- src/test/resources/testng.xml
> Changes to get execution parameters from ExecutionConstants.properties file

- pom.xml
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesDragAndDropTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationbartestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardpagetestcases/EditContentFormTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardpagetestcases/EditContentRecentlyCreatedTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardpagetestcases/EditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardpagetestcases/FilterShowRecentActivityTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardpagetestcases/ShowHideSiteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/siteconfigpagetestcases/PreviewSyncTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/AddNewFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/CopyPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/CopyPasteIntoFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/CutPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DeleteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DuplicateOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteEmptyTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/AddNewUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/DeleteUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/PaginationOfListOfUsersTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/LoginPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/pages/UsersPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
> Fixed some selectors/ids/and xpaths broken for failed test cases on testng.xml test cases suite

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Craftercms1248Test.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/CopyPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DuplicateOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteEmptyTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
- src/test/resources/testngcomplexscenarios.xml
…Craftecms1248.java (suite testngcomplexscenarios.xml), tested on latest version of crafter studio and running `mvn clean test`  command
Resolved issues with broken ids for cases in the suite testng.xml
> Resolved issues with broken ids for Crafter3LoadTest1Script.java and Craftecms1248.java

- src/test/java/org/craftercms/studio/test/cases/dashboardpagetestcases/EditContentFormTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardpagetestcases/EditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/AddNewContentSectionDfaultsTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/CutPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DeleteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DuplicateOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteEmptyTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/DeleteSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/DesignOfUsersPageTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/PaginationOfListOfSitesTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/SitesPerPageTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/UsersPerPageTest.java
- src/test/java/org/craftercms/studio/test/pages/UsersPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/testng.xml
… to CreateSiteEmptyTest Class
> Resolved some NotSuchElement errors for css selectors and improvement to CreateSiteEmptyTest Class

- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/CutPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DeleteOptionTest.java
Added some improvements with wartime for some test cases
> Adding some improvements on wait time for some test cases

- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DuplicateOptionTest.java
- src/test/java/org/craftercms/studio/test/pages/MyRecentActivityFramePage.java
<test name="Delete Option Test">
<classes>
<class
name="org.craftercms.studio.test.cases.sitespagetestcases.CreateSiteEmptyTest" />
<class
name="org.craftercms.studio.test.cases.sitecontentbartestcases.DeleteOptionTest" />
<class
name="org.craftercms.studio.test.cases.sitespagetestcases.DeleteSiteTest" />
</classes>
</test> 
<test name="Duplicate Option Test">
<classes>
<class
name="org.craftercms.studio.test.cases.sitespagetestcases.CreateSiteEmptyTest" />
<class
name="org.craftercms.studio.test.cases.sitecontentbartestcases.DuplicateOptionTest" />
<class
name="org.craftercms.studio.test.cases.sitespagetestcases.DeleteSiteTest" />
</classes>
</test> 
The following test cases were verified:
<test name="Design Of Create Site Page Test">
<classes>
<class …
> Added fixes to the next test cases:

- src/test/java/org/craftercms/studio/test/cases/dashboardpagetestcases/EditContentRecentlyCreatedTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/ChangePasswordUserTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/LoginPage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
EditContentRecentlyCreatedTest.java
ChangePasswordUserTest.java
The latest should resolve the login dependent test cases like API test cases and all UI test cases that use admin user on the login page or login api calls
> Added fixes for the next studio UI test cases:

- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
-DeleteSiteTest
-CancelCreateSiteProcessTest
Added some improvements to selectors on SharedUIElements.properties
> Added fixes for the next test cases:

- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/CutPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/DuplicateOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/EditUserTest.java
- src/test/java/org/craftercms/studio/test/pages/AccountManagementPage.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/resources/SharedUIElements.properties
Also merged some conflicts on DashboardPage.java
>  Added fixes for latest test execution (failed test cases)

- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/resources/SharedUIElements.properties
-showAboutUs
-showDocumentation
> Added fixes for the next failed test cases:

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
> Added some improvements to the test case:

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
-CreateSiteWithWebSiteEditorialBluePrintTest
-Crafter3LoadTest1Script
> Added fixes for the next case on latest execution:

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationbartestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteEmptyTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/DeleteSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/DeleteUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/EditUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/UsersPerPageTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
> Added fixes for latest failed test cases and improvements to xpaths

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationbartestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteEmptyTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/cases/sitespagetestcases/DeleteSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/DeleteUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userspagetestcases/EditUserTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/common.properties
-Crafter3LoadTest1Script.java
-PublishingSiteTest.java
-CreateSiteWithWebSiteEditorialBluePrintTest.java
-DeleteSite.test
-CreateSiteEmpty.test
-DeleteUser.test
-EditUser.test
-Deleted unused properties file
-Modified some xpaths and locators on SharedUIElements.properties
> Added some changes for next test cases:

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testngcomplexscenarios.xml
Added new test case for issue craftercms/craftercms#1557
Merge branch 'master' of https://github.com/craftercms/test-suite
> Added new test case for issue craftercms/craftercms#1557

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/ChangeStateOfPreviousPublishedContent.java
> Resolved codacy issues

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/ChangeStateOfPreviousPublishedContent.java
Added Fixes to ChangeStateOfPreviousPublishedContent Test Case to fix race conditions
> Added Fixes to ChangeStateOfPreviousPublishedContent Test Case

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/resources/SharedUIElements.properties
> Change hardcoded strings and clean code.

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/sitecontentbartestcases/CutPasteContentTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/resources/SharedUIElements.properties
Added fixes to the next failed test cases:
Crafter3LoadTest1Script
CutPasteContentTest
> Added fixes to the next failed test cases:

- src/test/java/org/craftercms/studio/test/cases/complexscenariostestcases/Crafter3LoadTest1Script.java
- src/test/resources/testng.xml
Clean hardcoded variables in CrafterLoadTest1Script Test Case
Delete from testing.xml the PreviewSyncTest, preview sync option is not longer available in siteconfig options
> Changes in test cases and testing.xml

- src/test/java/org/craftercms/studio/test/api/objects/GroupManagementAPI.java
- src/test/java/org/craftercms/studio/test/cases/api/DeleteGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/api/GetGroupsPerSiteAPITest.java
- src/test/java/org/craftercms/studio/test/utils/FakeSMTPServerManager.java
- src/test/resources/testng.xml
- src/test/resources/testngAPI.xml
- src/test/resources/testngSanityTest.xml
- src/test/resources/testngcomplexscenarios.xml
Added new API test cases related to GroupManagement API:
-DeleteGroupAPITest
-UpdatedGroupAPITest
-GetGroupsPerSiteAPITest
Added fixes for failed test cases and reported issues related to those
> Added new API test cases related to GroupManagement API

- src/test/java/org/craftercms/studio/test/utils/JsonTester.java
https://github.com/craftercms/craftercms/issues/1601
> Added CSRF cookie & header for all API calls

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewContentEntryTest.java
Added fixes for the AddNewContentEntryTest.
> Added fixes for the AddNewContentEntryTest.

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/HistoryOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/PaginationOfListOfSitesTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/resources/ExecutionConstants.properties
- src/test/resources/testng.xml
- src/test/resources/testngAPI.xml
- src/test/resources/testngSanityTest.xml
- src/test/resources/testngcomplexscenarios.xml
CopyPasteContentTest, HistoryOptionTest and PaginationOfListOfSitesTest
-Changed timeout from 21secs to 25 secs
> -Added fixes for the next failed test cases:

- src/test/java/org/craftercms/studio/test/api/objects/SecurityAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/SiteManagementAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetSitesPerUserAPITest.java
- src/test/resources/testngAPI.xml
GetSiteAPITest
GetSitesPerUserTest
> Added the new API test cases:

- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddFileNameTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/resources/SharedUIElements.properties
ContentTypesAddFileNameTest
ChangeStateOfPreviousPublishedContent
Modify Xpaths
> Added fixes to the failed test cases

- README.md
> Update README.md deleted the ":" replaced by "="

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/DeleteSiteTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
Delete failing isElementPresent methods.
> Added Fixes to Failed test Cases

- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateLoginInToStudio.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testngSanityTest.xml
Added test case to cover ticket https://github.com/craftercms/craftercms/issues/1435
> Added AutomateLoginInToStudio test case

- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateCreatingSiteUsingWebsiteEditorialBlueprint.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteEmptyTest.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testngSanityTest.xml
Test Case created to cover ticket https://github.com/craftercms/craftercms/issues/1445
> Added AutomateCreatingSiteUsingWebsiteEditorialBlueprint Test Case 

- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
Added fixes to the failed test case ChangeStateOfPreviousPublishedContent, this is the test cases that is getting stuck the automation.
> Added fixes to the ChangeStateOfPreviousPublishedContent Test Case

- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
Added fixes to changeStateOfPReviousPublishedContent and clean code.
Erase hardcoded xpaths and delete commented code.
> Added fixes to changeStateOfPReviousPublishedContent and clean code

- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceChildContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromDesktopTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDropdownTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddGroupedCheckBoxesTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddInputTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddItemSelectorTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddLabelTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddRepeatingGroupTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddRichTextEditorTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/RenameParentPageAndPublishChildTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
-Change isElementPresent method, causes automation is unstable on some cases.
-Fixes for General test cases: RenameParenPageAndPublishChildTest.
-Fixes on testng.xml for contentTypeAdd Controls Test Cases
> Added fixes to the Failed test cases of daily executions.

- src/test/java/org/craftercms/studio/test/cases/BaseTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteIntoFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DeleteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceChildContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromCMISRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromDesktopTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/EditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/log4j2-test.xml
- CopyPasteIntoFolderTest
- DeleteContentTest
- ContentTypesAddDataSourceChildContentTest
- ContentTypesAddDataSourceImageUploadedFromCMISRepositoryTest
- ContentTypesAddDataSourceImageUploadedFromDesktopTest
- ContentTypesAddDataSourceImageUploadedFromRepositoryTest
- DeleteOptionTest
- EditOptionTest
- CreateSiteWithWebSiteEditorialBluePrintTest
> Refactoring for test cases:

- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDateTimeTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DependenciesOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DuplicateOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/EnableDisableEditingInContextTest.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
ContentTypesAddDateTimeTest
DependenciesOptionTest
DuplicateOptionTest
EnableDisableEditingInContextTest
> Refactor the next test cases clases: 

- src/test/java/org/craftercms/studio/test/cases/BaseTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardtestcases/RecentActivityFilterShowTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/TryToDeleteUserConnectedTest.java
- src/test/java/org/craftercms/studio/test/pages/UsersPage.java
- DeleteOptionTest
- RecentActivityFilterShowTest
- TryToDeleteUserConnectedTest.java
> Refactor for test cases:

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/HistoryOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/ShowAboutUsTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/ShowDocumentationTest.java
- src/test/java/org/craftercms/studio/test/cases/loginlogouttestcases/LogOutTest.java
- src/test/java/org/craftercms/studio/test/cases/loginlogouttestcases/LoginTest.java
- src/test/java/org/craftercms/studio/test/cases/loginlogouttestcases/WrongLoginTest.java
- src/test/java/org/craftercms/studio/test/pages/LoginPage.java
-HistoryOptionTest
-ShowAboutUsTest
-ShowDocumentationTest
-LoginTest
-LogOutTest
-WrongLoginTest
>  Refactored the next test cases classes:

- src/test/java/org/craftercms/studio/test/cases/BaseTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DeleteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDateTimeTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardtestcases/DesignOfWorkflowStateSectionTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardtestcases/EditContentThroughDashboardEditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/previewpagetestcases/DesignOfPreviewPageTest.java
- src/test/java/org/craftercms/studio/test/cases/previewtoolstestcases/DesignOfPreviewToolsPanelTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
PublishingSiteTest
DesignOfWorkflowStateSectionTest
EditContentThroughDashboardEditOptionTest
DesignOfPreviewPageTest
DesignOfPreviewToolsPanelTest
>  Refactor the next test cases classes:

- src/test/java/org/craftercms/studio/test/cases/dashboardtestcases/RecentActivityItemTypesSectionTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardtestcases/ShowHideSiteContentTest.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
RecentActivityItemTypesSectionTest
ShowHideSiteContentTest
Added new method for waitUntilSidebarCloses on WebDriverManager class
> Refactored the next test cases classes:

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/DesignOfCreateSitePageTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/PaginationOfListOfSitesTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/SitesPerPageTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/ValidationsOfCreateSiteFieldsTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/AddNewUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/PaginationOfListOfUsersTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/SearchUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/ShowUsersPageTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/UsersPerPageTest.java
DesignOfCreateSitePageTest
PaginationOfListOfSitesTest
SitesPerPageTest
ValidationsOfCreateSiteFieldsTest
AddNewUserTest
PaginationOfListOfUsersTest
SearchUserTest
ShowUsersPageTest
UsersPerPageTest
> Refactor the next test cases:

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardtestcases/EditContentThroughDashboardEditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/UsersPerPageTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
-AddNewFolderTest
-UsersPerPageTest
-DashboardPage class
> Refactored the next test cases classes and general classes:

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewContentEntryTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceChildContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromCMISRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromDesktopTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddFileNameTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DuplicateOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/EditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardtestcases/EditContentThroughDashboardEditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/DeleteSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/EditUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/UsersPerPageTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
-EditUserTest
-PublishingSiteTest
-DuplicateOptionTest
-EditOptionTest
-AddNewFolderTest
Added new method to wait for delete site dialog closes
Modified the DeleteSite class to use method of above
> Added fixes and refactoring for the next test cases

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewFolderTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
-AddNewFolderTest
-AddNewContentEntryTest
Implemented validation for expandHome method when home is already expanded
> Added fixes for the next test cases classes:

- src/test/java/org/craftercms/studio/test/api/objects/AuditAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/ClipboardAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/ContentAssetAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/PublishAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/SecurityAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/SiteManagementAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/ContentExistsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/CreateFolderAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/DeleteSiteAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetAuditLogAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetItemsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetLoggersAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetSitesPerUserAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/MemoryAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/PublishStatusAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/SetLoggerStateAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/StatusAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/SyncFromRepoAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/ValidateSessionAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/VersionAPITest.java
- src/test/resources/testngAPI.xml
Addition of 401 unauthorized tests:
Delete Site
Get Sites Per User
Get Site
Get Audit Log
Added test:
Content Exists
Fixed unauthorized access test issues in:
GetLoggersAPITest
MemoryAPITest
SetLoggerStateAPITest
StatusAPITest
ValidateSessionAPITest
VersionAPITest
> Resolving unauthorized API testing changes + misc. tests

- pom.xml
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
-Crafter3LoadTest1Script.java
Also resolved some issues with contextclick method on WebDriverManager
> Added fixes and refactoring for the next test case class

- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
-Added some fixes for usingContextMenu method on WebDriverManager class
-Removed incognito test mode, it provokes some fails with chrome window on setup @ beforeclass methods
> Added some fixes for usingContextMenu method on WebDriverManager class

- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDateTimeTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/RenameParentPageAndPublishChildTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
-RenameParentPageAndPublishChildTest
-CopyAndPasteContentTest
Also, added some improvements to content type save click wait for notification after click.
Changed send key by sendText when a new control is added to a existing content page
> Refactoring for the next test cases classes:

- src/test/java/org/craftercms/studio/test/api/objects/ContentAssetAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/DependencyAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/SiteManagementAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetAvailableBlueprintsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetCannedMessageAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetContentAtPathAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetDependantItemsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetSimpleDependenciesAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/RenameFolderAPITest.java
- src/test/resources/testngAPI.xml
**Content Asset API**
Get Content at Path
Rename Folder
Create Folder
**Site Management API**
Get Available Blueprints
Get Canned Message
SiteExists
**Dependency API**
Get Dependent Items
Get Simple Dependencies
> Adding new Studio API Tests

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/FilesLocations.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
- src/test/resources/testngcomplexscenarios.xml
-Added wait condition for totally render of the History Dialog
-Added warn log message when some is wrong on the content type edition (contenttype test cases)
-Modified the Testng.xml for testing
-TakeScreenShot method for failed exceptions
-Changing right click related methods to use xpath directly instead the webelement param
-Added new property on shareui properties file
-Restored the testng.xml to run all the test cases into it
-Fixes for CrafterLoad3Test class
-Deleting while conditions for PublishingSiteTest class, now using driverManager.waitUntilAttributeContains method
> Added the next test cases improvements:

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/DesignOfCreateSitePageTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/AddNewUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/DesignOfUsersPageTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/EditUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/ShowUsersPageTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/resources/testng.xml
-CutPasteContentTest
-DeleteOptionTest
-DesignOfCreateSitePageTest
-DesignOfWorkflowStateSectionTest
-DuplicateOptionTest
-EditContentThroughDashboardEditOptionTest
-EditContentTest
-EditOptionTest
-EnableDisableEditingInContextTest
-RecentActivityFilterShowTest
-HistoryOptionTest
-PublishingSiteTest
-ShowHideSiteContentTest
-ValidationsOfCreateSiteFieldsTest
-WrongLoginTest
-DependenciesOptionTest
-AddNewUserTest
-DeleteUserTest
-EditUserTest
-DesignOfUsersPageTest
-UsersPerPageTest
-PaginationOfListOfUsersTest
-PaginationOfListOfSitesTest
-SitesPerPageTest
-ShowAboutUsTest
-ChangePasswordUserTest
-AddNewContentSectionDefaultsTest
-ShowUsersPageTest
-ContentTypesAddLabelTest
-ContentTypesAddPageOrderTest
-ContentTypesAddFileNameTest
-ContentTypesAddAutoFileNameTest …
> Added refactor for XPATHS used on the next test cases:

- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/resources/SharedUIElements.properties
TryToDeleteUserConnectedTest
LoginTest
LogOutTest
AddNewContentEntryTest
AddNewFolderTest
CancelCreateSiteProcessTest
CopyPasteContentTest
CopyPasteIntoFolderTest
CreateSiteEmptyTest
DeleteSiteTest
ContentTypesDragAndDropTest
DeleteContentTest
DesignOfPreviewPageTest
ShowDocumentationTest
ContentTypesAddInputTest
ContentTypesAddRepeatingGroupTest
ContentTypesAddTextAreaTest
ContentTypesAddRichTextEditorTest
ContentTypesAddDropdownTest
ContentTypesAddDateTimeTest
ContentTypesAddCheckBoxTest
ContentTypesAddGroupedCheckBoxesTest
ContentTypesAddItemSelectorTest
ContentTypesAddImageTest
ContentTypesAddVideoTest
> Refactor of new IDs and verify test Cases:  

- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
Changes to ChangeStateOfPreviousPublishedContent to run on linux machine.
Change some IDs
> Refactor of the next test cases:

- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/testngcomplexscenarios.xml
Resolved some failure lines on crafter3loadtest1script class
Also deleted some unused lines and spaces on class of above
Added improvements on methods of dashboardpage.java class
Added some improvements on webdrivermanager.java class
> Added some improvements to crafter3LoadTest test case class

- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/RenameParentPageAndPublishChildTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/DeleteSiteTest.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/resources/SharedUIElements.properties
And added some improvements to RenameParentPageAndPublishChild test
Added new method deleteAllSites on HomePage.java
> Added improvements to deletesite page and methods related to it, also added new elements paths

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewContentEntryTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewContentSectionDefaultsTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteIntoFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DeleteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/EditContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/EditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardtestcases/EditContentThroughDashboardEditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/dashboardtestcases/RecentActivityFilterShowTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/RenameParentPageAndPublishChildTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/MyRecentActivityPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
Refactor test cases (change IDs and call methods)
> Refactor test cases (change IDs and call methods)

- src/test/resources/SharedUIElements.properties
Fixed non-valid xpath related to the testngcomplexscenarios.xml test suite
> Changed non-valid xpath for Publish Dialog> Submit button

- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateCreatingSiteUsingWebsiteEditorialBlueprint.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testngcomplexscenarios.xml
Fix wrong IDs.
Fix AutomateCreatingSiteUsingWebsiteEditorialBlueprint test case.
> Refactor Test Cases and IDs.

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/DeleteUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/EditUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/PaginationOfListOfUsersTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/UsersPerPageTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/pages/UsersPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testngcomplexscenarios.xml
Added the next wait conditions identified:
this.driverManager.waitUntilPublishMaskedModalCloses();         and this.driverManager.waitUntilElementHasPublishedIcon(); Removed refresh call between publish requests
Also, changed the way of how we are deleting the users, currently, we deleted all the users existing except the admin user (on test executions related to users creation)
Added new IDs to xpaths (totally done with the refactor)
> Added some wait conditions between several publish requests for some pages in the same tree.

- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateCheckItemsInSiteConfig.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateCreatingSiteUsingWebsiteEditorialBlueprint.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateOpeningStudioInActualBrowser.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testngSanityTest.xml
Test Case: AutomateCheckItemsInSiteConfig
Ticket: https://github.com/craftercms/craftercms/issues/1448
Test Case: AutomateOpeningStudioInActualBrowser
Ticket: https://github.com/craftercms/craftercms/issues/1434
Add and refactor the UI Elements.
> Added Automated test cases to cover tickets:

- pom.xml
- src/test/java/org/craftercms/studio/test/api/objects/ClipboardAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/DependencyAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/CopyItemAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/CutItemAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetDependenciesAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetItemsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/PasteItemAPITest.java
- src/test/resources/testngAPI.xml
**Clipboard API tests created**
Copy Item
Cut Item
Get Items
Paste Item
**DependencyAPI finished**
Get Dependencies
> Studio API Clipboard calls

- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateVerifyingNoErrorsPresentInWebsiteEditorialBPHomePage.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testngSanityTest.xml
Added the next test case:
AutomateVerifyingNoErrorsPresentInWebsiteEditorialBPHomePage
To cover ticket: 
https://github.com/craftercms/craftercms/issues/1446
Also added in the testngSanitytest.xml
Added New Xpath Elements
> Added a test case 

- src/test/java/org/craftercms/studio/test/api/objects/ActivityAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/WorkflowAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/CreateJobsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetGoLiveItemsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetUserActivityAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetWorkflowAffectedPathsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GoDeleteAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GoLiveAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/RejectAPITest.java
- src/test/resources/testngAPI.xml
**Activity**
Get User Activity
**Workflow**
Create Jobs
Get Go Live Items
Get Workflow Affected Paths
Go Delete
Go Live
> Studio API test case additions

- initialSetupCheckForTestScript.bat
- initialSetupCheckForTestScript.sh
Improvements to pretest scripts proposed by vita:
-If temp folder exists> delete it
-After the check of above, create temp folder and go to temp, also run the rest of steps
-Removed the the check if the craftercms folder exists because we are sure that the temp folder is newly created all the time
> Changes to Pretest Scripts of the description (check temp folder exists)

- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAuthorUser.java
- src/test/resources/testng.xml
VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAuthorUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:91
Modify the testing.xml and add the created test case.
> Added new test case

- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithDeveloperUser.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithDeveloperUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:92
Modify the testing.xml to add the created test case.
> Added test case:

- initialSetupCheckForTestScript.bat
- initialSetupCheckForTestScript.sh
-added 'call' call for gradle process on windows
-modified some info texts and change directories missed
> Added some improvements to the pretest scripts:

- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateVerifyingNoErrorsPresentInWebsiteEditorialBPHomePage.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheApplicationRedirectstoTheSiteConfigPageWhenTheSiteConfigOptionIsClicked.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithReviewerUser.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithPublisherUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:93
Modify the testing.xml and add the created test case.
VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithReviewerUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:94
Modify the testing.xml and add the created test case.
VerifyTheApplicationRedirectstoTheSiteConfigPageWhenTheSiteConfigOptionIsClicked
To Cover Crafter CMS Integration Test spreadsheet test case ID:155
Modify the testing.xml and add the created test case.
> Added test cases

- src/test/resources/testng.xml
> Fix Testng.xml

- src/test/java/org/craftercms/studio/test/api/objects/DeploymentAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/BulkGoLiveAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetAvailablePublishingChannelsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetDeploymentHistoryAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetScheduledItemsAPITest.java
- src/test/resources/testngAPI.xml
Bulk Go Live
Get available publishing channels
Get deployment history
Get scheduled items
> Studio API adding Deployment section tests

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteIntoFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceChildContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromCMISRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromDesktopTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/RenameParentPageAndPublishChildTest.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateCheckingNoErrorsDisplayedInTheDashboard.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/PaginationOfListOfSitesTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/SitesPerPageTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
Added the next changes:
-Added some XPaths changes on content types and fixes for some failed test cases related to testng.xml suite on windows
-Added scroll down call for content type test cases (where data sources are added)
-Modified the scrolldown call to get more pixels
-Modified the waituntilpopupishidden method on WebDriverManager class
> Added several improvements and fixes for paths and windows failed test cases

- initialSetupCheckForTestScript.sh
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteIntoFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/previewtoolstestcases/DesignOfPreviewToolsPanelTest.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
> Adding the next windows fixes for chrome executions:

- src/test/java/org/craftercms/studio/test/cases/apitestcases/PostActivityAPITest.java
- src/test/resources/testngAPI.xml
> Studio API Post Activity test

- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheApplicationDisplaysTheProperAvailableOptionsWhenRightClickIsPerformedOnAnyElementOfThePagesStructureWithAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheApplicationDisplaysTheProperAvailableOptionsWhenRightClickIsPerformedOnAnyElementOfThePagesStructureWithDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheApplicationDisplaysTheProperAvailableOptionsWhenRightClickIsPerformedOnAnyElementOfThePagesStructureWithPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheApplicationDisplaysTheProperAvailableOptionsWhenRightClickIsPerformedOnAnyElementOfThePagesStructureWithReviewerUser.java
- src/test/resources/testng.xml
Edit test case:
VerifyTheApplicationDisplaysTheProperAvailableOptionsWhenRightClickIsPerformedOnAnyElementOfThePagesStructureWithAdminUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:96
VerifyTheApplicationDisplaysTheProperAvailableOptionsWhenRightClickIsPerformedOnAnyElementOfThePagesStructureWithAuthorUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:98
Modify the testing.xml and add the created test case.
VerifyTheApplicationDisplaysTheProperAvailableOptionsWhenRightClickIsPerformedOnAnyElementOfThePagesStructureWithDeveloperUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:99
Modify the testing.xml and add the created test case. …
> Edit and add new test cases

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/HistoryOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/EditUserTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
Added fixes for ChangeStateOfPreviousPublishedContent test case (on Windows + Chrome)
Removed hardcoded (missing) paths
Removed commented codes
Added some improvements on DashboardPage and PreviewPage classes
> Added fixes and improvements for test classes of description:

- src/test/java/org/craftercms/studio/test/api/objects/SiteManagementAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/CreateSiteGitRepoAPITest.java
- src/test/resources/testngAPI.xml
> Removing Deleted API Call from test suite

- initialSetupCheckForTestScript.bat
- initialSetupCheckForTestScript.sh
Added scripts improvements to displays all the outputs on a logfile and the results of each gradle process on a results file (for Windows and Linux/Mac)
> Added Pre-Test Scripts Improvements of description

- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheApplicationRedirectstoTheSiteConfigPageWhenTheSiteConfigOptionIsClicked.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithReviewerUser.java
- src/test/resources/testng.xml
Refactor the test cases class names. 
VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAuthorUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:22
Modify the testing.xml and add the created test case.
VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingDeveloperUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:23
Modify the testing.xml and add the created test case.
VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingPublisherUser
To Cover Crafter CMS Integration Test spreadsheet test case ID:24
Modify the testing.xml and add the created test case.
VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageS …
> Added New Test Cases:

- initialSetupCheckForTestScript.bat
- initialSetupCheckForTestScript.sh
Added some improvements to rename the terminal window title and for windows to close all the non-used terminal windows that does not allow to delete temporal folder
> Added some improvements to Pre-Test Scripts for windows and Mac

- initialSetupCheckForTestScript.bat
- initialSetupCheckForTestScript.sh
Removed the pause on windows script since we are able to close all the terminal windows
Added some [INFO] outputs and comments
> Added some improvements and removed the pause on windows script

- src/test/java/org/craftercms/studio/test/cases/accountmanagementtestcases/ShowAccountManagementTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/ShowSitesPageTest.java
- src/test/java/org/craftercms/studio/test/pages/AccountManagementPage.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/java/org/craftercms/studio/test/pages/UsersPage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
-Added new test case: ID: 4 of Workbook: Studio - Contextual Navigation
Test Name: Verify that the application shows the sites page when user clicks on sites contextual navigation bar option
-Added new test case: ID: 1 of Workbook: Studio - Contextual Navigation
Test Name: Verify that the application shows the account management page when user clicks on settings contextual navigation bar option
> Added new test cases of description:

- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithReviewerUser.java
- src/test/java/org/craftercms/studio/test/pages/UsersPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added changes for xpaths used on the content type test cases
Added some fixes for failed test cases of 02/05
Refactored some test cases methods
> Added some fixes and improvements for changed xpaths:

- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithReviewerUser.java
Simplified some code lines in the test cases and removed non-valid right click validations.
Added some fixes for failed test case.
> Added improvements of description:

- src/test/java/org/craftercms/studio/test/api/objects/SecurityAPI.java
- src/test/java/org/craftercms/studio/test/api/objects/UserManagementAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/ChangePasswordAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetUserPerSiteAPITest.java
Logout updated to match API call (no username/password required)
Change Password test 404 case removed, test structure changed
Get users per site test structure changed
> Studio API User Management test updates

- initialSetupCheckForTestScript.bat
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
-Added improvement to crafterload3scripttest class when try to click on Sidebar
-Added improvement to close the other terminal windows opened by startup and stop processes (on the pretest script on windows)
> Added the improvements of description:

- src/test/java/org/craftercms/studio/test/api/objects/ContentAssetAPI.java
- src/test/java/org/craftercms/studio/test/utils/JsonRequest.java
https://github.com/craftercms/craftercms/issues/1859
> Fixed issue for multipart requests

- initialSetupCheckForTestScript.bat
Added some changes to the windows pretest script to close all windows opened by previous gradlew proccesses.
> Added the changes of the description:

- src/test/java/org/craftercms/studio/test/cases/DeliveryBaseTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/VerifyThatNoBluePrintErrorsDisplayedWhenCreateSite.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateVerifyingNoErrorsPresentInWebsiteEditorialBPHomePage.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTestForDeliveryCheck.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/testng.xml
- src/test/resources/testngcomplexscenarios.xml
craftercms/craftercms#1877
craftercms/craftercms#1869
Added some new classes and improvements for run through code the init-site script of crafter-delivery/bin
> Added test case classes for the next tickets:

- README.md
Changes required to let know that those configuration variables are needed (for delivery test cases and for execution of scripts like init-site)
>  Added changes to README.md file 

- src/test/java/org/craftercms/studio/test/api/objects/GroupManagementAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/AddUserToGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/CreateGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/DeleteGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetUsersPerGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/RemoveUserFromGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/UpdateGroupAPITest.java
Updated to include the new Site Not Found 404 tests, as well as other misc. test updates
> Updating Group Management Studio API Tests

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTestForDeliveryCheck.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
deleted a IsElementPresent condition changed by waituntil condition for the submit button when try to delete an element
> Added fix to crafter3loadtest class

- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatPageIsNotOnLive.java
- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatPageIsOnLive.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
-Restructured the package of delivery test cases
-Added some changes on the WebDriverManager class
> Refactoring the delivery package set on the same level than the studio package

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DuplicateOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTestForDeliveryCheck.java
- src/test/java/org/craftercms/studio/test/pages/UsersPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
Added some changes to assert the messages returned by the init-site script for windows and linux (checking if the curl is installed on linux case)
> Added some assertions of the description:

- src/test/java/org/craftercms/studio/delivery/test/cases/verification/VerifyThatPageIsNotOnLive.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
Changed test names, also added text of the cause of assertion fails on the init-site method
> Added improvements of the description:

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewContentEntryTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteIntoFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/EditContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DuplicateOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/previewpagetestcases/DesignOfPreviewPageTest.java
- src/test/java/org/craftercms/studio/test/cases/previewtoolstestcases/PresetEachDesignTest.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
Removed page refresh call after click on preview link of just created site, it causes fails on some test cases.
> Added fixes for edge executions

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithReviewerUser.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
Added fixes to the next test cases classes:
VerifyRightClickOptionsOfAPagesUnderPageStructureUsingAuthorUser.java
VerifyRightClickOptionsOfAPagesUnderPageStructureUsingDeveloperUser.java
VerifyRightClickOptionsOfAPagesUnderPageStructureUsingPublisherUser.java
VerifyRightClickOptionsOfAPagesUnderPageStructureUsingReviewerUser.java
VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAdminUser.java
VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAuthorUser.java
VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingDeveloperUser.java
VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingPublisherUser.java
VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingReviewerUser.j …
> Added fixes for pending test cases on the testng.xml suite

- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatCopiedAndPastedLongTreeArticleIsOnLive.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTestForDeliveryCheck.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added new test classes for the ticket: #1894
Created the next new test cases:
org.craftercms.studio.test.cases.contenttestcases.CopyPasteLargeTreesTest
org.craftercms.delivery.test.cases.verification.VerifyThatCopiedAndPastedLongTreeArticleIsOnLive
Added new methods to WebDriverManager class
Fixed some assertion conditions on init-site call method
Added new ui xpaths and values on the ShareUIElements.properties
Added new test cases to the testng.xml suite
> Added the next changes and new test cases classes of description. 

- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
Added the correct validation for site already exists on delivery when execute the init-site.bat on windows
> Added improvement of description.

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheApplicationRedirectstoTheSiteConfigPageWhenTheSiteConfigOptionIsClicked.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithReviewerUser.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
Added fix for last failed test cases on unix (also for windows).
Added method to check if a folder or tree is not expanded then perform the click over it.
> Added the fixes and improvements of description.

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteIntoFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
Added fixes for next test cases:
CopyAndPasteIntoFolderTest 
CopyPasteLargeTreeTest
On Edge webbrowser
> Added the fixes of description for windows edge execution 

- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatCutAndPastedLongTreeArticleIsOnLive.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteEmptyTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTestForDeliveryCheck.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added changes for CopyPasteLargeTreesTest
Added new test clasess for ticket: craftercms/craftercms#1895
-CutPasteLargeTreesTest.java
-VerifyThatCutAndPastedLongTreeArticlesIsOnLive.java
Covered scenario of bug craftercms/craftercms#1915 on the test case of above
Added new methods for WebDriverManager class
Changes some ids and xpaths on the SharedUI properties file
> Added new test cases to cover the ticket #1895

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteIntoFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTestForDeliveryCheck.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
Added fixes for next test cases:
-CopyPasteIntoFolder
-CopyPasteLargeTreeTest
-CutPasteLargeTreeTest
-ChangeStateOfPreviousPublishedContent
-CreateSiteUsingWebSiteBluePrintTest
> Added fixes for last execution test cases

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAPagesUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
Added some improvements to check if sidebar is already opened on sitedropdown test cases
> Added some improvements for check if sidebar is already opened

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteLargeTreesTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
-Added fixes for Windows execution failed test cases.
-Added fix for cutandpastelongtrees test.
-Added fix for changeStateOfPreviousPublishedContent test.
-Added some enhancements for chrome executions.
> Added the changes of description.

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteContentWithSharedComponentsTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DependenciesCalculationRefersToAnItemTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
Added the asssertion for the item text be the correct on the dependecies dialog.
Added comments for the added code lines
> Added changes of above for dependencies calculation test case

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DependenciesCalculationItemRefersToTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/testng.xml
Added new test case DependenciesCalculationItemRefersToTest to cover the ticket 1937 also added to testng.xml suite
> Added new test case to cover ticket #1937

- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
Added waitfor event before expand home tree.
> Added fix for last execution (failed test cases on Mac)

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/DeleteOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/TryToDeleteUserConnectedTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/UsersPage.java
Failed test cases: tryToDeleteUserConnectedTest.java
DeleteOptionTest.java
> Added fixes for failed test cases on Windows execution.

- pom.xml
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DependenciesCalculationItemRefersToTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/RenameViaFormTest.java
Added fixes for failed test cases around 1985, also updated version of surefire plugin on POM.xml
> Added fixes for Windows executions and changed some dependencies versions

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DependenciesCalculationItemRefersToTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/RenameViaFormTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTestForDeliveryCheck.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
Added improvements to other test cases, and added fix for RenameViaFormTest case for windows.
> Added fixes for RenameViaFormTest test case failed

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteToFolderTest.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added the new test case class: CutPasteToFolderTest.java
Also added the new test case to the testng.xml test suite
> Added new test case to cover the ticket #2005

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderTest.java
- src/test/resources/SharedUIElements.properties
Added new test case to the testing.xml test suite.
> Added new test case CopyPasteToFolderTest to cover the ticket #2015.

- src/test/resources/testng.xml
Added the newly created test case to the testing.xml suite (missed)
> Added missing test tag on the test suite to cover 2015

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DeleteContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DependenciesCalculationItemRefersToTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/HistoryOptionTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
Added fixes for latest failed test cases on testng.xml suite, also added some improvements on DependenciesCalculationRefersToTest class
> Added fixes for failed test case of latest execution.

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderWithCollisionTest.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added new test case class CopyPasteToFolderWithCollisionTest.java to cover: #2028.
Also added test to testng.xml suite.
> Added new test case to cover ticket 2028 

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/RenameViaFormPageMoveNameRenameTest.java
- src/test/resources/testng.xml
Added new test case: RenameViaFormPageMoveNameRenameTest to cover the ticket: #2030.
Also added the test to testng.xml suite.
> Added new test case to cover ticket #2030

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderWithCollisionPageTest.java
- src/test/resources/testng.xml
Added new test case: CopyPasteToFolderWithCollisionPageTest to cover the ticket: 2038
Also added test case to the testng.xml suite.
> Added new test case to cover the ticket: #2038

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteContentWithSharedComponentsTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/HistoryOptionTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
Added changes on the next test cases:
-AddNewFolderTest
-CopyAndPasteContentWithSharedComponentsTest
-HistoryOptionTest
> Added fixes failed test cases on last execution.

- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatCutAndPastedLongTreeArticleIsOnLive.java
- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatRenamedAndPublishedArticleIsOnLive.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderPageCopyToFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderWithCollisionPageTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderWithCollisionTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteToFolderPageMoveToFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteToFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DependenciesCalculationItemRefersToTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DependenciesCalculationRefersToAnItemTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/RenameViaFormPageMoveNameRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/RenameViaFormTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added new test case FileRenameThenPublishTest and VerifyThatRenamedAndPublishedArticleIsOnLive to cover ticket 2043.
Also added to testng.xml and performed some methods rename.
> Added new test case to cover the ticket 2043

- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatRenamedAndPublishedArticleIsOnLiveRequestingPageHTML.java
- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatRenamedAndPublishedArticleIsOnLiveRequestingPageName.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishPageRenameTest.java
- src/test/resources/testng.xml
Added new test case FileRenameThenPublishPageRenameTest to cover the ticket: 2046.
Renamed some test classes.
Also added to the testng.xml suite.
> Added the test case to cover the ticket 2046

- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatRenamedRenamedAndPublishedArticleIsOnLiveRequestingPageHTML.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderPageCopyToFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderWithCollisionPageTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteToFolderPageMoveToFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddAutoFileNameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddCheckBoxTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceChildContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromCMISRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromDesktopTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDataSourceImageUploadedFromRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDateTimeTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddDropdownTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddFileNameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddGroupedCheckBoxesTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddImageTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddInputTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddItemSelectorTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddLabelTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddPageOrderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddRepeatingGroupTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddRichTextEditorTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddTextAreaTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesAddVideoTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesDragAndDropTest.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
- Added test case VerifyThatRenamedRenamedAndPublishedArticleIsOnLiveRequestingPageHTML to cover ticket 2049.
- Also added to the testng.xml suite.
- Added some changes on the test cases related to contenttypes.
> Added test case to cover ticket 2049

- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatRenamedRenamedAndPublishedArticleIsOnLiveRequestingPageName.java
- src/test/java/org/craftercms/studio/test/api/objects/UserManagementAPI.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteToFolderWithCollisionPageTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteToFolderPageMoveToFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameRenameThenPublishPageRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/RenameViaFormTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttypepagetestcases/ContentTypesDragAndDropTest.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateCheckingNoErrorsDisplayedInTheDashboard.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added FileRenameRenameThenPublishPageRenameTest test to cover ticket 2055.
Also added to the testng.xml test suite.
Added fixes for test cases failed on the last execution.
Modified some changed xpaths.
> Added new test case to cover ticket 2055

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CopyPasteContentWithSharedComponentsTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameRenameThenPublishPageRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishPageRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
-Added fixes for failed test cases related with changes on blueprints for ticket: #1933.
-Changed some xpaths locators.
> Added changes related to ticket 1933

- src/test/java/org/craftercms/studio/test/api/objects/ActivityAPI.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
Added fixes for failed test cases on the last execution. 
Added changes to api call test case: ActivityAPI because a param changed.
Also for the test of above we report the bug: 2071.
> Added fixes for latest test cases failed and test case related with ticket 2071

- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatRenamedAndPublishedArticleIsOnLiveRequestingPageHTML.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameAgainAndDeleteTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishTest.java
- src/test/resources/testng.xml
Added new test case FileRenameAgainAndDeleteTest to cover the ticket #2061.
Also added to the testng.xml suite.
> Added new test case to cover the ticket 2061

- src/test/java/org/craftercms/delivery/test/cases/verification/VerifyThatRenamedAndPublishedArticleIsOnLiveRequestingPageName.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameAgainAndDeletePageRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishPageRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/HistoryOptionTest.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/ExecutionConstants.properties
- src/test/resources/testng.xml
Added new test case FileRenameAgainAndDeletePageRenameTest to cover the ticket: 2064.
Also added the test to the testng.xml suite.
> Added new test case to cover ticket #2064.

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifySitesPageWithSitesAndWithoutSitesTest.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added test case VerifySitesPageWithSitesAndWithoutSitesTest to cover the ticket: 2087. 
Also added to the testng.xml test suite
> Added new test case to cover ticket #2087

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifySitesPageWithSitesAndWithoutSitesTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateSitesWithEachBlueprint.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added test case VerifyStudioAllowsToCreateSitesWithEachBlueprint to cover ticket 2095.
Also added to the testng.xml test suite.
> Added test case to cover ticket #2095

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateSitesWithEachBlueprintTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioShowEachValidationOfFieldsForCreateSiteTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/ExecutionConstants.properties
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added test case VerifyStudioShowEachValidationOfFieldsForCreateSiteTest to cover ticket #2106.
Also added new test to testng.xml suite.
Added changes for failed test case when try to execute init-site script.
> Added new test case to cover ticket #2106

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CancelCreateSiteProcessTest.java
- src/test/resources/testng.xml
Added test case CancelCreateSiteProcess to cover ticket: #2099. 
Added test case to testng.xml test suite.
> Added test case to cover ticket: #2099.

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CancelCreateSiteProcessTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToDeleteASiteCreatedTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToFilterNumberOfSitesPerPage.java
- src/test/resources/testng.xml
Added test case VerifyStudioAllowsToFilterNumberOfSitesPerPage to covers ticket: 2124.
Added to the testng.xml test suite.
> Added test case to cover ticket 2124.

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyThatPaginationOfSiteListWorksProperly.java
- src/test/resources/testng.xml
Added new test case to cover ticket #2127.
Also added to the testng.xml test suite
> Added new test case to cover ticket #2127.

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToGoToPreviewPageWhenClickOnPreviewLinkTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyThatPaginationOfSiteListWorksProperlyTest.java
- src/test/resources/testng.xml
Added new test case: VerifyStudioAllowsToGoToPreviewPageWhenClickOnPreviewLinkTest to cover ticket: 2128.
Also added to the testng.xml suite.
> Added new test case to cover ticket #2128

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToGoToDashboardPageWhenClickOnDashboardLinkTest.java
- src/test/resources/testng.xml
Added new test case VerifyStudioAllowsToGoToDashboardPageWhenClickOnDashboardLinkTest to cover ticket #2129.
Also added test to testng.xml suite.
> Added new test case to cover ticket #2129

- src/test/java/org/craftercms/studio/test/api/objects/ContentAssetAPI.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameRenameThenPublishPageRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishPageRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioallowsToCreateASiteBasedOnARemoteGitRepositoryWithBasicAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/FilesLocations.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/ExecutionConstants.properties
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added new test case VerifyStudioallowsToCreateASiteBasedOnARemoteGitRepositoryWithBasicAuthenticationTypeTest to cover ticket #2139.
Also added to testng.xml suite.
> Added new test case to cover #2139

- src/test/java/org/craftercms/studio/test/api/objects/ContentAssetAPI.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameRenameThenPublishPageRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishPageRenameTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/FileRenameThenPublishTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/PublishingSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioallowsToCreateASiteBasedOnARemoteGitRepositoryWithBasicAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioallowsToCreateASiteBasedOnARemoteGitRepositoryWithTokenAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/FilesLocations.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/ExecutionConstants.properties
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng.xml
Added new test case VerifyStudioallowsToCreateASiteBasedOnARemoteGitRepositoryWithTokenAuthenticationTypeTest to cover ticket #2141.
Also added to the testng.xml suite
> Added new test case to cover ticket #2141

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/AddNewContentAndPublishContentTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/ChangeStateOfPreviousPublishedContent.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/RenameParentPageAndPublishChildTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/resources/SharedUIElements.properties
Added some improvement to select a category when create a Page - Category landing page on site using WebsiteEditorial (test cases)
> Added some improvements related to ticket: #2196

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioAllowsToPublishAContentProperlyTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioAllowsToUnlockAContentTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioDisplaysAsLockedTheContentCorrectlyTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioDisplaysProperContentStateTest.java
- src/test/resources/testng_StudioContent.xml
Added new test case VerifyThatStudioDisplaysProperContentStateTest to cover test case # 24 on Integration Document - Studio Content sheet.
Also added new test cases:
VerifyThatStudioAllowsToPublishAContentProperlyTest related to # 23
VerifyThatStudioAllowsToUnlockAContentTest related to # 22
VerifyThatStudioDisplaysAsLockedTheContentCorrectlyTest related to # 21
Also added those test cases to testng_StudioContent.xml suite.
>  Added new test cases to cover test case # 24 of integration test document

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioAllowsToChangeTemplateProperlyTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioContent.xml
Added new test case VerifyThatStudioAllowsToChangeTemplateProperlyTest to cover test case # 15 from Studio - Content sheet of Integration Document.
Also added the test to testng_StudioContent.xml.
> Added new test case to cover test case # 15 from Studio - Content sheet of Integration Document.

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioDisplaysProperlyTheHistoryForAContentTest.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioContent.xml
Added new test case VerifyThatStudioDisplaysProperlyTheHistoryForAContentTest to cover test case # 16 of the Studio - Content sheet on Integration Test Document.
Also added the new test case to testng_StudioContent.xml suite.
> Added new test case to cover test case # 16 Site- Content sheet of Integration Test Document

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioDisplaysFieldsAsReadOnlyOnViewFormTest.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioContent.xml
Added new test case VerifyThatStudioDisplaysFieldsAsReadOnlyOnViewFormTest to cover test case # 10 Studio Content sheet from Integration Test document.
Added test case to testng_StudioContent.xml.
> Added new test case to cover test case # 10 Studio - Content sheet of Integration Test document.

- src/test/java/org/craftercms/studio/test/cases/DeliveryBaseTest.java
- src/test/java/org/craftercms/studio/test/cases/StudioBaseTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioDisplaysTheProperInfoOnContentToolTipTest.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioContent.xml
Added new test case VerifyThatStudioDisplaysThePropeInfoOnContentToolTipTest to cover test case # 9 of Studio - Content sheet.
Also added to testng_StudioContent.xml suite.
Added some improvements to DriverManager class.
> Added new test case to cover test case #9 of Studio - Content sheet from Integration Test Document.

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioDisplaysTheProperPrevioInfoForAContentTest.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioContent.xml
Added new test case VerifyThatStudioDisplaysTheProperPrevioInfoForAContentTest to cover test case # 8 of Studio Content sheet on Integration test document.
Also added new test case to testng_StudioContent.xml suite.
> Added new test case to cover test case # 8 of Studio Content sheet from Integration test document.

- src/test/java/org/craftercms/studio/test/api/objects/GroupManagementAPI.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/DeleteGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/RemoveUserFromGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DependenciesCalculationItemRefersToTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/DependenciesCalculationRefersToAnItemTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatCopyOperationHandlesDependenciesAndComponentsCorrectlyTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatDuplicateOperationHandlesDependenciesAndComponentsCorrectlyTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioDisplaysAsLockedTheContentCorrectlyTest.java
- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatStudioDisplaysProperlyTheHistoryForAContentTest.java
- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
Added some fixes for failed test cases on last execution.
Added some improvements on API test cases for Groups api.
> Added some fixes and improvements for failed test cases on last execution

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/VerifyThatApplicationDisplaysPublishStatusDialogTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioContextualNavigation.xml
Added new test case VerifyThatApplicationDisplaysPublishStatusDialogTest to cover test case # 6 of the Studio - Contextual Navigation sheet from the Integration test document.
Also added new test case to the testng_StudioContextualNavigation.xml
> Added new test case to cover test case # 6 of the Studio - Contextual Navigation sheet from the Integration test document.

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/VerifyThatApplicationDisplaysTheSearchPageWhenSearchOptionIsClickedTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
Added new test case VerifyThatApplicationDisplaysTheSearchPageWhenSearchOptionIsClickedTest to cover test case # 7 of Studio - Contextual Navigation sheet from Integration test document.
Also added new test case to testng_StudioContextualNavigation.xml suite.
> Added new test case  to cover test case # 7 of Studio - Contextual Navigation sheet from Integration test document.

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/VerifyThatApplicationDisplaysThePreviewToolsWhenSearchOptionIsClickedTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioContextualNavigation.xml
Added new test case VerifyThatApplicationDisplaysThePreviewToolsWhenSearchOptionIsClickedTest to cover test case # 8 of Studio - Contextual Navigation from Integration test document.
Also added test case to testng_StudioContextualNavigation.xml suite.
> Add new test case to cover test case # 8 of Studio - Contextual Navigation from Integration test document.

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/VerifyThatApplicationDisplaysTheInContextEditIconProperlyTest.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioContextualNavigation.xml
Added new test case VerifyThatApplicationDisplaysTheInContextEditIconProperlyTest to cover test case # 9 of the Studio - Contextual Navigation sheet from Integration Test Document.
Also added the new test case to the testng_StudioContextualNavigation.xml
> Added new test case to cover test case # 9 of the Studio - Contextual Navigation sheet from Integration Test Document.

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/VerifyThatCompareHistoryWorksProperly.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/Crafter3LoadTest1Script.java
- src/test/resources/testng_StudioContextualNavigation.xml
Added new test case VerifyThatCompareHistoryWorksProperly to cover ticket # 2357
Also added the new test case to the testng_StudioContextualNavigation.xml
> Added new test case VerifyThatCompareHistoryWorksProperly to cover ticket # 2357

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/VerifyThatApplicationDisplaysTheProperSetOfAvailableOptionsTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/VerifyThatCompareHistoryWorksProperly.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioContextualNavigation.xml
Added new test case VerifyThatApplicationDisplaysTheProperSetOfAvailableOptionsTest to cover test case # 10 of Studio - Contextual Navigation sheet of integration test document.
Also added new test case to the testng_StudioContextualNavigation.xml.
> Added new test caseto cover test case # 10 of Studio - Contextual Navigation sheet of integration test document.

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteAfterAFailedCreateSiteWithLinkUpstreanRemoteGitRepoWithBasicAuthTest.java
- src/test/resources/ExecutionConstants.properties
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioSites.xml
Added new test case VerifyStudioAllowsToCreateASiteAfterAFailedCreateSiteWithLinkUpstreanRemoteGitRepoWithBasicAuthTest to cover ticket 2371.
Added new test case to testng_StudioSites.xml suite.
> Added new test case to cover ticket # 2371.

- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedAndRequestPublishPageUnderPageStructureUsingReviewerUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingReviewerUser.java
- src/test/resources/testng_StudioGeneral.xml
- src/test/resources/testng_StudioLoginLogout.xml
- src/test/resources/testng_StudioRemoteReposScenarios.xml
Added fixes for failed test cases on 04/10/2018.
Also changed wrong test suite name on RemoteRepoScenarios suite file.
Also, non-changed failed test cases related to bugs (bugs no resolved yet)
> Added fixes for failed test cases on 04/10/2018 and some changes on suite files.

- src/test/java/org/craftercms/studio/test/api2/objects/UserManagementAPI2.java
- src/test/java/org/craftercms/studio/test/api2/objects/UsersManagementAPI2.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/GetUserSiteRoleAPI2Test.java
Changed url on Current Authenticated User Site Roles scenarios (Positive and negative). Related to failed test cases on 2018/10/09 execution.
> Changes to api2 failed test cases related to fixed tickets around CurrentAuthenticatedUserSiteRoles scenarios

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/CutPasteToFolderPageMoveToFolderTest.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyRightClickOptionsOfAnEditedPageUnderPageStructureUsingAuthorUser.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
Added fixes for last execution (failed test case), the cause is the content tooltip does not allow to click the authors folder.
> Added fixes for last execution (failed test case)

- src/test/java/org/craftercms/studio/test/cases/apitestcases/AddUserToGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/CreateGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/DeleteGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetGroupsAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetGroupsPerSiteAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetUsersPerGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/RemoveUserFromGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/UpdateGroupAPITest.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAdminUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithAuthorUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithDeveloperUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithPublisherUser.java
- src/test/java/org/craftercms/studio/test/cases/sitedropdowntestcases/VerifyTheSideBarDropdownOptionsUsingWebEditorialBlueprintWithReviewerUser.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_StudioAPI.xml
Fixed failed test cases on last execution of 3.0.18.
Removed test cases already discussed outdated for api1.
Fixed a broken xpath on sanitytest suite.
> Fixed failed test cases on last execution of 3.0.18.

- pom.xml
Upgrade Jackson version to 2.9.8
https://github.com/craftercms/craftercms/issues/2799
> CRAFTERCMS-2799

- src/test/java/org/craftercms/studio/test/api2/objects/RepositoryAPI2.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/AddRemoteAPI2Test.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/ListRemotesAPI2Test.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/PullFromRemoteAPI2Test.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/PushToRemoteAPI2Test.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/RebuildDBRemoteAPI2Test.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/RemoveRemoteAPI2Test.java
- src/test/java/org/craftercms/studio/test/utils/JsonResponse.java
- src/test/resources/ExecutionConstants.properties
- src/test/resources/testng_StudioAPI2.xml
https://github.com/craftercms/craftercms/issues/3070
> Remote API2 Test Cases

- src/test/java/org/craftercms/studio/test/api2/objects/RepositoryAPI2.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/AddRemoteAPI2Test.java
Add test repository already exist api2
> Add test repository already exist api2

- src/test/java/org/craftercms/studio/test/api/objects/ActivityAPI.java
- src/test/java/org/craftercms/studio/test/api2/objects/RepositoryAPI2.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/AddRemoteAPI2Test.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/ListRemotesAPI2Test.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/PullFromRemoteAPI2Test.java
- src/test/java/org/craftercms/studio/test/cases/apitestcases/GetUserRolesAPITest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioShowEachValidationOfFieldsForCreateSiteTest.java
- src/test/java/org/craftercms/studio/test/pages/HomePage.java
> Updates 3.1.1

- README.md
- selenium_grid/docker-compose.yaml
- src/test/resources/SharedUIElements.properties
* Add selenium-grid using docker-compose.
* Updates on READMe
* Updates on WebElement locators
> Add Selenium grid 

- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/VerifyThatCompareHistoryWorksProperly.java
- src/test/resources/SharedUIElements.properties
https://github.com/craftercms/craftercms/issues/3423 
Add check for the presence of the `Revert` button when is clicked and the History dialog refreshed.
> Check for the revert button occurrences when revert button is clicked

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatImageCropWorksProperlyTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/EditOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/HistoryOptionTest.java
- src/test/java/org/craftercms/studio/test/cases/contextualnavigationtestcases/VerifyThatApplicationDisplaysPublishStatusDialogTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_no_parallel.xml
- src/test/resources/testng_parallel.xml
* Updates to use `clickElement` method in some test cases
*  Add a testng suite, `testng_no_parallel.xml`,  for the tests that cannot be run in parallel
* Updates for selectors and timeouts.
> Updates develop

- pom.xml
Remove dependencies no longer needed, add io-commons.
now Snyk is happy :smile:
> Remove dependencies no longer needed, add io-commons

- src/test/resources/testng_parallel.xml
> Remove HEAD and upstream/develop lines from merge

- src/test/java/org/craftercms/studio/test/cases/siteconfigtestcases/VerifyThatStudioAllowsToAddRemoteRepositoryAndPushAndPullFromRemoteTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteAfterAFailedCreateSiteWithLinkUpstreanRemoteGitRepoWithBasicAuthTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteBasedOnARemoteGitRepositoryWithBasicAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteBasedOnARemoteGitRepositoryWithNoneAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteBasedOnARemoteGitRepositoryWithPrivateKeyAuthenticationTypeOnLocalRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteBasedOnARemoteGitRepositoryWithTokenAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteWithLinkToUpstreamRemoteGitRepoWithBasicAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteWithLinkToUpstreamRemoteGitRepoWithPrivateKeyAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteWithLinkToUpstreamRemoteGitRepoWithTokenAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateSiteBasedOnBluePrintThenPushToRemoteGitRepoTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/ExecutionConstants.properties
- src/test/resources/testng_StudioRemoteReposScenarios.xml
- src/test/resources/testng_StudioSiteConfig.xml
- src/test/resources/testng_parallel.xml
https://github.com/craftercms/craftercms/issues/3456
> Use parameters in testng remote repos suite

- src/test/resources/testng_StudioRemoteReposScenarios.xml
- src/test/resources/testng_parallel.xml
Rename parameter in testng suite file
> Rename parameter in testng suite file

- src/test/java/org/craftercms/studio/test/pages/DashboardPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
https://github.com/craftercms/craftercms/issues/3442
> Updates for new upload file dialog

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyThatDuplicateOperationHandlesDependenciesAndComponentsCorrectlyTest.java
- src/test/java/org/craftercms/studio/test/cases/generaltestcases/VerifyThatNoBluePrintErrorsDisplayedWhenCreateSite.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateCheckItemsInSiteConfig.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateCheckingNoErrorsDisplayedInTheDashboard.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateCreatingSiteUsingWebsiteEditorialBlueprint.java
- src/test/java/org/craftercms/studio/test/cases/sanitytesttestcases/AutomateVerifyingNoErrorsPresentInWebsiteEditorialBPHomePage.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CancelCreateSiteProcessTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteEmptyTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithHeadlessBlogBluePrintTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/CreateSiteWithWebSiteEditorialBluePrintTestForDeliveryCheck.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteAfterAFailedCreateSiteWithLinkUpstreanRemoteGitRepoWithBasicAuthTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteBasedOnARemoteGitRepositoryWithBasicAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteBasedOnARemoteGitRepositoryWithNoneAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteBasedOnARemoteGitRepositoryWithPrivateKeyAuthenticationTypeOnLocalRepositoryTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteBasedOnARemoteGitRepositoryWithTokenAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteWithLinkToUpstreamRemoteGitRepoWithBasicAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteWithLinkToUpstreamRemoteGitRepoWithPrivateKeyAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteWithLinkToUpstreamRemoteGitRepoWithTokenAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateSiteBasedOnBluePrintThenPushToRemoteGitRepoTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateSitesWithEachBlueprintTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToDeleteASiteCreatedTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioShowEachValidationOfFieldsForCreateSiteTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/EditUserTest.java
- src/test/java/org/craftercms/studio/test/pages/CreateSitePage.java
- src/test/java/org/craftercms/studio/test/pages/PreviewPage.java
- src/test/java/org/craftercms/studio/test/pages/SiteConfigPage.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/SharedUIElements.properties
- src/test/resources/testng_parallel.xml
Updates for create site tests:
* Change some CreateSitePage methods to fluent and change in the test case steps.
* Add utils methods in WebDriverManager
* Update testing repos url
> Updates create site test

- src/test/java/org/craftercms/studio/test/cases/contenttestcases/VerifyBulkUploadAssetsWorksProperlyTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/EditUserTest.java
- src/test/java/org/craftercms/studio/test/cases/userstestcases/VerifyLanguageSettingsTest.java
- src/test/java/org/craftercms/studio/test/utils/FilesLocations.java
- src/test/java/org/craftercms/studio/test/utils/WebDriverManager.java
- src/test/resources/testng_no_parallel.xml
- src/test/resources/testng_parallel.xml
* Fix for deleting a site instead of a user
* Update a password for Edit User test
* Bulk Upload test: Update file locations. Adding scripts will recreate the site context we need to check the log(catalina.out) further than usual, 3 times the normal is enough. Move the bulk test to no_parallel tests
> Update bulk upload test

- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateASiteBasedOnARemoteGitRepositoryWithTokenAuthenticationTypeTest.java
- src/test/java/org/craftercms/studio/test/cases/sitestestcases/VerifyStudioAllowsToCreateSiteBasedOnBluePrintThenPushToRemoteGitRepoTest.java
- src/test/resources/testng_parallel.xml
Updates for create site with remotes test.
> Update missing remote tests

- src/test/java/org/craftercms/studio/test/api2/objects/AuditAPI2.java
- src/test/java/org/craftercms/studio/test/api2/objects/RepositoryAPI2.java
- src/test/java/org/craftercms/studio/test/cases/api2testcases/DashboardContentAPI2Test.java
> Fixes API 1 tests
